os: linux
dist: bionic
language: node_js
node_js:
  - '12.18.1'

addons:
  chrome: stable

script:
  - 'commitlint-travis'
  - 'npm run lint'
  - 'npm test'
  - 'npm run browserstack'
  - 'npm run build'
  - 'npm run test:integration'
